// <auto-generated />
using System;
using IParcial_Prog5_Bingo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IParcial_Prog5_Bingo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240630021706_AddInitial")]
    partial class AddInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parcial1.Models.Carton", b =>
                {
                    b.Property<int>("IdCarton")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_carton");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarton"));

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_modificacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdJuego")
                        .HasColumnType("int")
                        .HasColumnName("ID_juego");

                    b.Property<int?>("IdJugador")
                        .HasColumnType("int")
                        .HasColumnName("ID_jugador");

                    b.Property<string>("Numeros")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdCarton")
                        .HasName("PK__carton__5C22245547B409F0");

                    b.HasIndex("IdJuego");

                    b.HasIndex("IdJugador");

                    b.ToTable("carton", (string)null);
                });

            modelBuilder.Entity("Parcial1.Models.ConfiguracionJuego", b =>
                {
                    b.Property<int>("IdConfiguracionJuego")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_configuracion_juego");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConfiguracionJuego"));

                    b.Property<int?>("CantidadBolas")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad_bolas");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_modificacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdTipoJuego")
                        .HasColumnType("int")
                        .HasColumnName("ID_tipo_juego");

                    b.Property<string>("PatronesGanadores")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Patrones_ganadores");

                    b.Property<decimal?>("PremioMayor")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Premio_mayor");

                    b.Property<string>("PremiosMenores")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Premios_menores");

                    b.HasKey("IdConfiguracionJuego")
                        .HasName("PK__configur__0D5EE67CA8DA09E2");

                    b.ToTable("configuracionJuego", (string)null);
                });

            modelBuilder.Entity("Parcial1.Models.ConfiguracionMetodoPago", b =>
                {
                    b.Property<int>("IdConfiguracionMetodoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_configuracion_metodo_pago");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConfiguracionMetodoPago"));

                    b.Property<decimal?>("ComisionAplicada")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("Comision_aplicada");

                    b.Property<string>("DatosRequeridos")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Datos_requeridos");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_modificacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdMetodoPago")
                        .HasColumnType("int")
                        .HasColumnName("ID_metodo_pago");

                    b.HasKey("IdConfiguracionMetodoPago")
                        .HasName("PK__configur__64E03234A6387560");

                    b.HasIndex("IdMetodoPago");

                    b.ToTable("configuracionMetodoPago", (string)null);
                });

            modelBuilder.Entity("Parcial1.Models.ConfiguracionNotificacion", b =>
                {
                    b.Property<int>("IdConfiguracionNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_configuracion_notificacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConfiguracionNotificacion"));

                    b.Property<string>("Destinatarios")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EventoNotificacion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Evento_notificacion");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_modificacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PlantillaMensaje")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)")
                        .HasColumnName("Plantilla_mensaje");

                    b.Property<string>("TipoNotificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Tipo_notificacion");

                    b.HasKey("IdConfiguracionNotificacion")
                        .HasName("PK__configur__3D28DD034576B01F");

                    b.ToTable("configuracionNotificacion", (string)null);
                });

            modelBuilder.Entity("Parcial1.Models.ConfiguracionPromocion", b =>
                {
                    b.Property<int>("IdConfiguracionPromocion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_configuracion_promocion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConfiguracionPromocion"));

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_modificacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdPromocion")
                        .HasColumnType("int")
                        .HasColumnName("ID_promocion");

                    b.Property<string>("RequisitosAplicacion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Requisitos_aplicacion");

                    b.Property<string>("TipoDescuento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Tipo_descuento");

                    b.Property<decimal?>("ValorDescuento")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Valor_descuento");

                    b.HasKey("IdConfiguracionPromocion")
                        .HasName("PK__configur__AE411E9188FCC682");

                    b.HasIndex("IdPromocion");

                    b.ToTable("configuracionPromocion", (string)null);
                });

            modelBuilder.Entity("Parcial1.Models.DetallePedido", b =>
                {
                    b.Property<int>("IdDetallePedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_detalle_pedido");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetallePedido"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal?>("Descuento")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_modificacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdPedido")
                        .HasColumnType("int")
                        .HasColumnName("ID_pedido");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("ID_producto");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Precio_unitario");

                    b.Property<decimal?>("TotalDetalle")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(22, 2)")
                        .HasColumnName("Total_detalle")
                        .HasComputedColumnSql("([Cantidad]*[Precio_unitario]-[Descuento])", false);

                    b.HasKey("IdDetallePedido")
                        .HasName("PK__detalleP__4FE41491BAF7FF05");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdProducto");

                    b.ToTable("detallePedido", (string)null);
                });

            modelBuilder.Entity("Parcial1.Models.Juego", b =>
                {
                    b.Property<int>("IdJuego")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_juego");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJuego"));

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("FechaJuego")
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_juego");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_modificacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("PrecioCarton")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Precio_carton");

                    b.Property<decimal?>("PremioMayor")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Premio_mayor");

                    b.Property<string>("PremiosMenores")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Premios_menores");

                    b.Property<string>("TipoJuego")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Tipo_juego");

                    b.HasKey("IdJuego")
                        .HasName("PK__juego__DC5CBBF13447BC72");

                    b.ToTable("juego", (string)null);
                });

            modelBuilder.Entity("Parcial1.Models.Jugador", b =>
                {
                    b.Property<int>("IdJugador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_jugador");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJugador"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Correo_electronico");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_modificacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_nacimiento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("Saldo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdJugador")
                        .HasName("PK__jugador__923936175D9C1978");

                    b.ToTable("jugador", (string)null);
                });

            modelBuilder.Entity("Parcial1.Models.MetodoPago", b =>
                {
                    b.Property<int>("IdMetodoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_metodo_pago");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMetodoPago"));

                    b.Property<decimal?>("Comision")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_modificacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdMetodoPago")
                        .HasName("PK__metodoPa__317DAC30B3886564");

                    b.ToTable("metodoPago", (string)null);
                });

            modelBuilder.Entity("Parcial1.Models.ParametrosGenerale", b =>
                {
                    b.Property<int>("IdParametro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_parametro");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdParametro"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_modificacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Valor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdParametro")
                        .HasName("PK__parametr__58394880CEB2B055");

                    b.ToTable("parametrosGenerales", (string)null);
                });

            modelBuilder.Entity("Parcial1.Models.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_pedido");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<string>("DireccionEnvio")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("Direccion_envio");

                    b.Property<string>("EstadoPedido")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Estado_pedido");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_modificacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_pedido")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdJugador")
                        .HasColumnType("int")
                        .HasColumnName("ID_jugador");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Metodo_pago");

                    b.Property<decimal?>("TotalPedido")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Total_pedido");

                    b.HasKey("IdPedido")
                        .HasName("PK__pedido__E337E2C38D02A2DE");

                    b.HasIndex("IdJugador");

                    b.ToTable("pedido", (string)null);
                });

            modelBuilder.Entity("Parcial1.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_producto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Disponibilidad")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_modificacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdProducto")
                        .HasName("PK__producto__13C163947A167D44");

                    b.ToTable("producto", (string)null);
                });

            modelBuilder.Entity("Parcial1.Models.Promocion", b =>
                {
                    b.Property<int>("IdPromocion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_promocion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPromocion"));

                    b.Property<string>("CodigoDescuento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Codigo_descuento");

                    b.Property<string>("Condiciones")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_fin");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_inicio");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_modificacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("PorcentajeDescuento")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("Porcentaje_descuento");

                    b.HasKey("IdPromocion")
                        .HasName("PK__promocio__F5B423599443693C");

                    b.ToTable("promocion", (string)null);
                });

            modelBuilder.Entity("Parcial1.Models.Resultado", b =>
                {
                    b.Property<int>("IdResultado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_resultado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdResultado"));

                    b.Property<int?>("BolaExtraida")
                        .HasColumnType("int")
                        .HasColumnName("Bola_extraida");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("FechaHoraExtraccion")
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_hora_extraccion");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_modificacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdCartonGanador")
                        .HasColumnType("int")
                        .HasColumnName("ID_carton_ganador");

                    b.Property<int?>("IdJuego")
                        .HasColumnType("int")
                        .HasColumnName("ID_juego");

                    b.HasKey("IdResultado")
                        .HasName("PK__resultad__CF43FCDF4660DA08");

                    b.HasIndex("IdCartonGanador");

                    b.HasIndex("IdJuego");

                    b.ToTable("resultado", (string)null);
                });

            modelBuilder.Entity("Parcial1.Models.Transaccion", b =>
                {
                    b.Property<int>("IdTransaccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_transaccion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTransaccion"));

                    b.Property<DateTime?>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_hora")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_modificacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdJuego")
                        .HasColumnType("int")
                        .HasColumnName("ID_juego");

                    b.Property<int?>("IdJugador")
                        .HasColumnType("int")
                        .HasColumnName("ID_jugador");

                    b.Property<decimal?>("Monto")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TipoTransaccion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Tipo_transaccion");

                    b.HasKey("IdTransaccion")
                        .HasName("PK__transacc__3811279475A1E44D");

                    b.HasIndex("IdJuego");

                    b.HasIndex("IdJugador");

                    b.ToTable("transaccion", (string)null);
                });

            modelBuilder.Entity("Parcial1.Models.Carton", b =>
                {
                    b.HasOne("Parcial1.Models.Juego", "IdJuegoNavigation")
                        .WithMany("Cartons")
                        .HasForeignKey("IdJuego")
                        .HasConstraintName("FK__carton__ID_juego__3F466844");

                    b.HasOne("Parcial1.Models.Jugador", "IdJugadorNavigation")
                        .WithMany("Cartons")
                        .HasForeignKey("IdJugador")
                        .HasConstraintName("FK__carton__ID_jugad__403A8C7D");

                    b.Navigation("IdJuegoNavigation");

                    b.Navigation("IdJugadorNavigation");
                });

            modelBuilder.Entity("Parcial1.Models.ConfiguracionMetodoPago", b =>
                {
                    b.HasOne("Parcial1.Models.MetodoPago", "IdMetodoPagoNavigation")
                        .WithMany("ConfiguracionMetodoPagos")
                        .HasForeignKey("IdMetodoPago")
                        .HasConstraintName("FK__configura__ID_me__75A278F5");

                    b.Navigation("IdMetodoPagoNavigation");
                });

            modelBuilder.Entity("Parcial1.Models.ConfiguracionPromocion", b =>
                {
                    b.HasOne("Parcial1.Models.Promocion", "IdPromocionNavigation")
                        .WithMany("ConfiguracionPromocions")
                        .HasForeignKey("IdPromocion")
                        .HasConstraintName("FK__configura__ID_pr__70DDC3D8");

                    b.Navigation("IdPromocionNavigation");
                });

            modelBuilder.Entity("Parcial1.Models.DetallePedido", b =>
                {
                    b.HasOne("Parcial1.Models.Pedido", "IdPedidoNavigation")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("IdPedido")
                        .HasConstraintName("FK__detallePe__ID_pe__628FA481");

                    b.HasOne("Parcial1.Models.Producto", "IdProductoNavigation")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK__detallePe__ID_pr__6383C8BA");

                    b.Navigation("IdPedidoNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("Parcial1.Models.Pedido", b =>
                {
                    b.HasOne("Parcial1.Models.Jugador", "IdJugadorNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdJugador")
                        .HasConstraintName("FK__pedido__ID_jugad__5CD6CB2B");

                    b.Navigation("IdJugadorNavigation");
                });

            modelBuilder.Entity("Parcial1.Models.Resultado", b =>
                {
                    b.HasOne("Parcial1.Models.Carton", "IdCartonGanadorNavigation")
                        .WithMany("Resultados")
                        .HasForeignKey("IdCartonGanador")
                        .HasConstraintName("FK__resultado__ID_ca__45F365D3");

                    b.HasOne("Parcial1.Models.Juego", "IdJuegoNavigation")
                        .WithMany("Resultados")
                        .HasForeignKey("IdJuego")
                        .HasConstraintName("FK__resultado__ID_ju__44FF419A");

                    b.Navigation("IdCartonGanadorNavigation");

                    b.Navigation("IdJuegoNavigation");
                });

            modelBuilder.Entity("Parcial1.Models.Transaccion", b =>
                {
                    b.HasOne("Parcial1.Models.Juego", "IdJuegoNavigation")
                        .WithMany("Transaccions")
                        .HasForeignKey("IdJuego")
                        .HasConstraintName("FK__transacci__ID_ju__4BAC3F29");

                    b.HasOne("Parcial1.Models.Jugador", "IdJugadorNavigation")
                        .WithMany("Transaccions")
                        .HasForeignKey("IdJugador")
                        .HasConstraintName("FK__transacci__ID_ju__4AB81AF0");

                    b.Navigation("IdJuegoNavigation");

                    b.Navigation("IdJugadorNavigation");
                });

            modelBuilder.Entity("Parcial1.Models.Carton", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("Parcial1.Models.Juego", b =>
                {
                    b.Navigation("Cartons");

                    b.Navigation("Resultados");

                    b.Navigation("Transaccions");
                });

            modelBuilder.Entity("Parcial1.Models.Jugador", b =>
                {
                    b.Navigation("Cartons");

                    b.Navigation("Pedidos");

                    b.Navigation("Transaccions");
                });

            modelBuilder.Entity("Parcial1.Models.MetodoPago", b =>
                {
                    b.Navigation("ConfiguracionMetodoPagos");
                });

            modelBuilder.Entity("Parcial1.Models.Pedido", b =>
                {
                    b.Navigation("DetallePedidos");
                });

            modelBuilder.Entity("Parcial1.Models.Producto", b =>
                {
                    b.Navigation("DetallePedidos");
                });

            modelBuilder.Entity("Parcial1.Models.Promocion", b =>
                {
                    b.Navigation("ConfiguracionPromocions");
                });
#pragma warning restore 612, 618
        }
    }
}
